# Generated by Django 4.1.7 on 2024-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="School"
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Number of events")),
                (
                    "teacher_contact",
                    models.CharField(max_length=10, verbose_name="Teacher Contact"),
                ),
                (
                    "details_json",
                    models.CharField(max_length=3000, verbose_name="Details as JSON"),
                ),
            ],
        ),
    ]
