# Generated by Django 4.1.7 on 2024-10-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="details_json",
        ),
        migrations.AddField(
            model_name="registration",
            name="details",
            field=models.CharField(default="", max_length=3000, verbose_name="Details"),
            preserve_default=False,
        ),
    ]
