# Generated by Django 4.1.7 on 2024-11-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_registration_teacher_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="school",
            field=models.CharField(max_length=100, verbose_name="School"),
        ),
    ]
